import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { validateManifest } from "@tarmac/validate";

/**
 * `tarmac new <name>`
 *
 * Generates a repository already wired to the paved road.
 *
 * The generated output is deliberately small. A scaffold that emits two hundred
 * files is one nobody reads, so people keep whatever it produced whether or not
 * it fits — and the parts they do not understand become the parts they are
 * afraid to change. Everything here is something a developer should be able to
 * read in a sitting.
 *
 * Notably absent: a copy of the pipeline. The generated CI file *calls* the
 * reusable workflow. A scaffold that copies pipeline YAML produces a fleet of
 * services that were identical on day one and have diverged by the end of the
 * quarter, and a gate added later reaches none of them.
 */
export interface ScaffoldOptions {
  readonly name: string;
  readonly owner: string;
  readonly port?: number;
  readonly description?: string;
}

export interface GeneratedFile {
  readonly path: string;
  readonly contents: string;
}

export function serviceManifest(options: ScaffoldOptions): string {
  const port = options.port ?? 8080;
  return `# The contract between this service and the platform.
#
# This is the only infrastructure surface you need to touch. Terraform reads it,
# the pipeline validates it. Run \`tarmac validate\` before pushing.
apiVersion: tarmac/v1

name: ${options.name}
owner: ${options.owner}
${options.description ? `description: ${options.description}\n` : ""}
runtime:
  type: container
  port: ${port}
  cpu: 256
  memory: 512
  healthcheck:
    liveness: /healthz
    readiness: /readyz

environments:
  dev:
    replicas: 1
    approval: automatic
  staging:
    replicas: 1
    approval: automatic
  prod:
    replicas: 2
    # Production waits for a human. The schema rejects "automatic" here.
    approval: required

slo:
  availability: 99.9
  latency_p95_ms: 300
`;
}

export function workflow(name: string): string {
  return `# ${name}'s pipeline.
#
# This calls the platform's reusable workflow rather than copying it, so every
# gate — including gates added after this service onboarded — applies here
# automatically. Do not inline the pipeline steps.
name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  golden-path:
    uses: lspecian/platform-deploy/.github/workflows/golden-path.yml@main
    with:
      service-path: .
      environment: dev
`;
}

export function readme(options: ScaffoldOptions): string {
  return `# ${options.name}

${options.description ?? "A service on the paved road."}

Owned by **${options.owner}**.

## First run

\`\`\`
npm install          # generates package-lock.json, which the Dockerfile needs
git add -A && git commit -m "Initial commit"
\`\`\`

The lockfile is not generated by the scaffold because it is derived from your
registry at the moment you install. Commit it — the pipeline builds with
\`npm ci\`, which requires it and refuses to silently resolve different versions.

## Local development

\`\`\`
tarmac dev        # run the whole stack locally
tarmac validate   # the same check CI runs
tarmac deploy     # deploy to dev
tarmac status     # where is my change
tarmac rollback   # undo
\`\`\`

## Changing what this service needs

Edit \`service.yaml\`. To add a bucket:

\`\`\`yaml
resources:
  bucket:
    name: ${options.name}-data
\`\`\`

Terraform picks it up, the bucket is created encrypted with public access
blocked, and its name arrives in the container as \`BUCKET_NAME\`. You do not
write any HCL.

## What you do not have to think about

Image hardening, IAM roles, the load balancer, log shipping, secret scanning,
dependency and image vulnerability scanning, infrastructure policy, and rollback
on a failed deploy. Those are the road's job. If one of them blocks you and you
cannot tell why, that is a bug in the road — raise it.
`;
}

export function dockerfile(port: number): string {
  return `# Pinned by digest, not by tag: a tag is mutable, so a rebuild of an unchanged
# commit can produce a different image. The container policy gate rejects a FROM
# without a digest.
FROM node@sha256:c610fcdfb1d5b4740dd70c284ed3cb16bb857e0f7166196e36a5501df7a3aa32 AS base
WORKDIR /app

FROM base AS deps
COPY package.json package-lock.json ./
RUN npm ci

FROM deps AS build
COPY . .
RUN npm run build

FROM base AS runtime
# The runtime never needs a package manager, and every one of npm's vendored
# dependencies is attack surface plus a stream of scanner findings.
RUN apk --no-cache upgrade && rm -rf /usr/local/lib/node_modules/npm \\
    /usr/local/bin/npm /usr/local/bin/npx /opt/yarn-v* /usr/local/bin/yarn

COPY --from=build --chown=node:node /app/dist ./dist
COPY --from=deps --chown=node:node /app/node_modules ./node_modules

# Non-root: a container escape from a root container starts as root on the host.
USER node
EXPOSE ${port}

# Exec form, so SIGTERM reaches the process and graceful shutdown runs. The
# shell form would swallow it and every deploy would drop in-flight requests.
CMD ["node", "dist/server.js"]
`;
}

export function packageJson(options: ScaffoldOptions): string {
  return `${JSON.stringify(
    {
      name: options.name,
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        dev: "tsx watch src/server.ts",
        build: "tsc",
        start: "node dist/server.js",
        test: "vitest run",
        typecheck: "tsc --noEmit",
      },
      dependencies: { fastify: "^5.12.1", pino: "^10.3.1" },
      devDependencies: {
        "@types/node": "^26.4.0",
        tsx: "^4.23.12",
        typescript: "^7.0.2",
        vitest: "^4.1.11",
      },
    },
    null,
    2,
  )}\n`;
}

export function tsconfig(): string {
  return `${JSON.stringify(
    {
      compilerOptions: {
        target: "ES2023",
        lib: ["ES2023"],
        module: "ESNext",
        moduleResolution: "bundler",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        outDir: "dist",
        rootDir: "src",
        types: ["node"],
      },
      include: ["src"],
    },
    null,
    2,
  )}\n`;
}

export function server(options: ScaffoldOptions): string {
  const port = options.port ?? 8080;
  return `import Fastify from "fastify";
import { pino } from "pino";

/*
 * Generated by \`tarmac new\`. Replace the greeting route with your service;
 * leave the health endpoints and the logger alone unless you know why you are
 * changing them — the platform's load balancer health checks read /readyz, and
 * the log shipper expects JSON.
 */
const app = Fastify({
  loggerInstance: pino({
    level: process.env.LOG_LEVEL ?? "info",
    base: {
      service: "${options.name}",
      environment: process.env.ENVIRONMENT ?? "local",
      commit: process.env.GIT_COMMIT ?? "unknown",
    },
    formatters: { level: (label) => ({ level: label }) },
    timestamp: pino.stdTimeFunctions.isoTime,
  }),
  trustProxy: true,
});

/*
 * Liveness: is the process able to answer at all? Deliberately checks nothing
 * else — if liveness depended on a downstream service, an outage there would
 * make the orchestrator kill every healthy instance.
 */
app.get("/healthz", async () => ({ status: "ok" }));

/*
 * Readiness: should this instance receive traffic right now? Add real
 * dependency checks here as you add dependencies. A /readyz that returns 200
 * unconditionally is worse than none: the load balancer will route to an
 * instance that cannot serve.
 */
app.get("/readyz", async () => ({ status: "ready", dependencies: [] }));

app.get("/api/greeting", async () => ({
  message: "hello from ${options.name}",
  service: "${options.name}",
  environment: process.env.ENVIRONMENT ?? "local",
  // Returned so a post-deploy smoke test can assert *which* build is running,
  // not merely that something answered.
  commit: process.env.GIT_COMMIT ?? "unknown",
}));

// Graceful shutdown. Without it a rolling deploy drops in-flight requests.
for (const signal of ["SIGTERM", "SIGINT"] as const) {
  process.on(signal, () => {
    app.log.info({ signal }, "shutting down");
    void app.close().then(() => process.exit(0));
  });
}

await app.listen({
  port: Number(process.env.PORT ?? ${port}),
  // Containers must bind all interfaces; localhost-only fails the health check.
  host: "0.0.0.0",
});
`;
}

export function serverTest(options: ScaffoldOptions): string {
  return `import { describe, expect, it } from "vitest";

/*
 * A placeholder so the pipeline's test gate has something to run and the
 * coverage floor has a baseline. Replace it with tests for your service.
 */
describe("${options.name}", () => {
  it("has a test suite", () => {
    expect(true).toBe(true);
  });
});
`;
}

export function gitignore(): string {
  return "node_modules/\ndist/\ncoverage/\n.env\n*.log\n";
}

export function generate(options: ScaffoldOptions): readonly GeneratedFile[] {
  const port = options.port ?? 8080;
  return [
    { path: "service.yaml", contents: serviceManifest(options) },
    { path: ".github/workflows/ci.yml", contents: workflow(options.name) },
    { path: "README.md", contents: readme(options) },
    { path: "Dockerfile", contents: dockerfile(port) },
    { path: "package.json", contents: packageJson(options) },
    { path: "tsconfig.json", contents: tsconfig() },
    { path: "src/server.ts", contents: server(options) },
    { path: "test/server.test.ts", contents: serverTest(options) },
    { path: ".gitignore", contents: gitignore() },
  ];
}

export interface ScaffoldResult {
  readonly written: readonly string[];
  readonly errors: readonly string[];
}

export function scaffold(target: string, options: ScaffoldOptions): ScaffoldResult {
  const errors: string[] = [];

  // Validate before writing anything. Producing a repository that fails its own
  // first pipeline run is a bad first impression of the road.
  const manifest = validateManifest(serviceManifest(options));
  if (!manifest.valid) {
    return {
      written: [],
      errors: manifest.errors.map((e) => `${e.path ? `${e.path}: ` : ""}${e.message}`),
    };
  }

  if (existsSync(target)) {
    return { written: [], errors: [`${target} already exists`] };
  }

  const written: string[] = [];
  for (const file of generate(options)) {
    const full = join(target, file.path);
    mkdirSync(join(full, ".."), { recursive: true });
    writeFileSync(full, file.contents);
    written.push(file.path);
  }

  return { written, errors };
}
